version: 0.0
os: linux
files:
  - source: /app/
    destination: /home/ubuntu/followeez/
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 3000
      runas: root
  BeforeInstall:
    - location: scripts/before_install
      timeout: 3000
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 3000
      runas: root


